In [1]:
import pandas as pd

# Load datasets

In [2]:
movies = pd.read_csv('/content/Netflix_Dataset_Movie.csv')
movies.head()

   Movie_ID  Year                          Name
0         1  2003               Dinosaur Planet
1         2  2004    Isle of Man TT 2004 Review
2         3  1997                     Character
3         4  1994  Paula Abdul's Get Up & Dance
4         5  2004      The Rise and Fall of ECW

In [3]:
ratings = pd.read_csv('/content/Netflix_Dataset_Rating.csv')
ratings.head()

   User_ID  Rating  Movie_ID
0   712664       5         3
1  1331154       4         3
2  2632461       3         3
3    44937       5         3
4   656399       4         3

# Merge the movie and ratings datasets

In [6]:
movie_ratings=pd.merge(movies,ratings)
movie_ratings.head()

   Movie_ID  Year                        Name  User_ID  Rating
0         2  2004  Isle of Man TT 2004 Review   927786       5
1         3  1997                   Character   712664       5
2         3  1997                   Character  1331154       4
3         3  1997                   Character  2632461       3
4         3  1997                   Character    44937       5

# Create pivot table: User_ID as index, Movie Name as columns, Ratings as values

In [7]:
movie_ratings=movie_ratings.pivot_table(index=['User_ID'],columns=['Name'],values='Rating')
movie_ratings.head()

Name,7 Seconds,A Little Princess,A Night at the Opera,ABC Primetime: Mel Gibson's The Passion of the Christ,Airplane II: The Sequel,Aqua Teen Hunger Force: Vol. 1,Carandiru,Chappelle's Show: Season 1,Character,Charlotte's Web,...,The Last Shot,The Love Letter,The Powerpuff Girls Movie,The Three Stooges: Sing a Song of Six Pants,The Weather Underground,Viva La Bam: Season 1,What the #$*! Do We Know!?,Winnie the Pooh: Springtime with Roo,Woman of the Year,X2: X-Men United
User_ID,,,,,,,,,,,,,,,,,,,,,
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,4.0
79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,...,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0
97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0

# Check if a movie contains the word 'Wild'

In [8]:
movies['Name'][movies['Name'].str.contains('Wild ')]

329                                            Wild Things
841                                     Reap the Wild Wind
2357                                       The Wild Angels
2389                                            Wild Style
2453                 Jane Goodall's Wild Chimpanzees: IMAX
2558     Mystery Science Theater 3000: The Wild World o...
2692                            How to Stuff a Wild Bikini
3706                     White Wolves: A Cry in The Wild 2
4029                                   Wild in the Country
4669                                        Wild Wild West
4896                          Nikki: Wild Dog of the North
5449     Wacky Babies & Tender Times: Marty Stouffer's ...
6002                                         Wild at Heart
6026                            The Wild Thornberrys Movie
7780                                  Touching Wild Horses
8367                                            Wild Palms
9361           Nature: Cloud: Wild Stallion of the Rockies
9562                                 Walk on the Wild Side
9846                                         Wild Things 2
9895                        Wild Australia: The Edge: IMAX
10141                                         The Wild One
10396                   Wild Things: Diamonds in the Rough
11118                                         Wild America
11180                                           Wild Cardz
11590                                       The Wild Child
14304                                        Wild Orchid 2
14909                                            Wild Bill
14943                                  Run the Wild Fields
15198                                            Wild Side
15271                                          Wild Orchid
15485          Sesame Street: Elmo's World: Wild Wild West
15639                                           Wild Reeds
15713                                            Wild Zero
15785                                    Wild Strawberries
16970                                 Mr. Toad's Wild Ride
17278                                            Wild Arms
17765    Where the Wild Things Are and Other Maurice Se...
Name: Name, dtype: object

# Choose a specific movie to find similar ones

In [9]:
movieName = movie_ratings['Character']
movieName

User_ID
6         NaN
7         NaN
79        NaN
97        NaN
134       NaN
           ..
2649370   NaN
2649378   NaN
2649388   NaN
2649426   NaN
2649429   NaN
Name: Character, Length: 141587, dtype: float64

# Find movies similar to the chosen one

In [10]:
similar_movies = movie_ratings.corrwith(movieName)
similar_movies = similar_movies.dropna()

# Display top similar movies

In [11]:
df = pd.DataFrame(similar_movies)
df.head(10)

                                                           0
Name
7 Seconds                                           0.213756
A Little Princess                                   0.490783
A Night at the Opera                                0.394196
ABC Primetime: Mel Gibson's The Passion of the ...  0.436011
Airplane II: The Sequel                             0.161782
Aqua Teen Hunger Force: Vol. 1                      0.468897
Carandiru                                           0.476641
Chappelle's Show: Season 1                          0.413645
Character                                           1.000000
Charlotte's Web                                     0.312324

#View sorted similarities

In [12]:
similar_movies.sort_values(ascending=False)

Name
Character              1.000000
Home Movie             0.654529
Scratch                0.645514
Invader Zim            0.642130
Regular Guys           0.619479
                         ...
Congo                  0.039844
Jade                   0.024712
Sweet November         0.019102
Duplex (Widescreen)   -0.017658
Jingle All the Way    -0.060900
Length: 81, dtype: float64